name: Run News Fetch and Broadcast

on:
  schedule:
    - cron: '0 9 * * *'  # 每天上午9點執行 (UTC時間)
  workflow_dispatch:

jobs:
  run-news-broadcast:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python 3.x
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  # 可調整你需要的版本

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run the main script
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      run: |
        python main.py
