name: Daily News Push

on:
  schedule:
    - cron: '0 1 * * *'  # 台灣時間早上 9 點
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Inject Secret and Run
        env:
          LINE_CHANNEL_ACCESS_TOKEN: ${{ secrets.LINE_CHANNEL_ACCESS_TOKEN }}
        run: |
          echo "LINE_CHANNEL_ACCESS_TOKEN = '${LINE_CHANNEL_ACCESS_TOKEN}'" > config.py
          python main.py
