name: Daily LINE News Broadcast

on:
  schedule:
    - cron: '0 0 * * *'  # UTC時間，每天0點執行 (台灣8點)

jobs:
  broadcast:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run news broadcast
        env:
          ACCESS_TOKEN: ${{ secrets.LINE_TOKEN }}
        run: python main.py
